name: CMake

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install gtest
      run: sudo apt install libgtest-dev

    - name: build
      run: cmake -B ./build

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: install gtest
      run: sudo apt install libgtest-dev
      
    - name: build
      run: cmake -B ./build
      
    - name: make
      run: cmake --build ./build

    - name: run-tests
      run: ./build/Google_tests/Google_tests
