name: CMake

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install gtest
      run: sudo apt install libgtest-dev lcov

    - name: build
      run: cmake -B ./build

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: install gtest
      run: sudo apt install libgtest-dev lcov
      
    - name: build
      run: cmake -Dtest=true -B ./build
      
    - name: make
      run: cmake --build ./build

    - name: run-tests
      run: ./build/Google_tests/Google_tests
      
  valgrind:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: install valgrind
      run: sudo apt-get install libgtest-dev valgrind
      
    - name: build
      run: cmake -Dtest=true -B ./build
      
    - name: make
      run: cmake --build ./build

    - name: run-tests
      run: valgrind ./build/Google_tests/Google_tests
      
  sanitaizer:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: install gtest
      run: sudo apt install libgtest-dev lcov
      
    - name: build
      run: cmake -Dsanitaizer_test=true -B ./build
      
    - name: run
      run: cmake --build ./build
